import CryptoKit
import Foundation

/// Verifies that a downloaded release archive was signed by whoever holds the
/// release key, before anything is unpacked or run.
///
/// The point is that GitHub is not the root of trust. An auto-updater that
/// only checks "GitHub served me this file" executes whatever an account
/// takeover puts there. The private key lives on the release machine and is
/// never uploaded, so a compromised repository can serve a tampered archive
/// but cannot produce a signature for it.
enum ReleaseSignature {
    /// Generated by `swift Scripts/signing.swift keygen`. Rotating this means
    /// existing installs can no longer verify new releases, so they would have
    /// to be replaced by hand — treat it as permanent.
    static let publicKeyBase64 = "uKckjrDZDmjxog29Px42MvAqWc50lxM1JMbAuywdLME="

    /// `signature` is base64 of the raw 64-byte Ed25519 signature, which is
    /// exactly what the signing script writes into the `.sig` file.
    static func isValid(data: Data, signature: String) -> Bool {
        let trimmed = signature.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let signatureBytes = Data(base64Encoded: trimmed),
              let keyBytes = Data(base64Encoded: publicKeyBase64),
              let key = try? Curve25519.Signing.PublicKey(rawRepresentation: keyBytes)
        else { return false }

        return key.isValidSignature(signatureBytes, for: data)
    }
}
